services:
  web:
    build: .
    volumes:
      - "./db.sqlite3:/src/db.sqlite3"
      - "./staticfiles:/src/staticfiles"
    env_file:
      - .env
  nginx:
    image: nginx:alpine
    links:
      - "web:web"
    volumes:
      - "./nginx/web.conf:/etc/nginx/conf.d/default.conf"
      - "./staticfiles:/src/staticfiles"
    ports:
      - "80:80"
